
services:
  db:
    image: postgres:14
    container_name: suprasport_db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5433"
    networks:
      suprasport_net:
        ipv4_address: 192.168.1.30

  superset:
    build: ./superset
    container_name: suprasport_superset
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      SUPERSET_WEBSERVER_PROTOCOL: "http"
      SUPERSET_WEBSERVER_ADDRESS: "0.0.0.0"
      SUPERSET_WEBSERVER_PORT: "8088"
      ENABLE_PROXY_FIX: "True"
    depends_on:
      - db
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    command:
      - /bin/bash
      - -c
      - |
        superset db upgrade &&
        superset fab create-admin \
            --username $ADMIN_USERNAME \
            --firstname $ADMIN_FIRSTNAME \
            --lastname $ADMIN_LASTNAME \
            --email $ADMIN_EMAIL \
            --password $ADMIN_PASSWORD &&
        superset init &&
        gunicorn -w 4 -k gevent --timeout 120 -b 0.0.0.0:8088 \
        --forwarded-allow-ips="*" "superset.app:create_app()"

    networks:
      suprasport_net:
        ipv4_address: 192.168.1.20

  telegram_bot:
    build: ./telegram_bot
    container_name: suprasport_bot
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      Y_Api_Key: "${Y_Api_Key}"
      CATALOG_ID: "${CATALOG_ID}"
    depends_on:
      - db
    networks:
      suprasport_net:
        ipv4_address: 192.168.1.40

  nginx:
    image: nginx:1.27.3
    env_file:
      - .env
    container_name: suprasport_nginx
    depends_on:
      - superset
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
     suprasport_net:
       ipv4_address: 192.168.1.10

volumes:
  postgres_data:
  superset_home:

networks:
  suprasport_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24