version: '3.8'

services:
  db:
    image: postgres:14
    container_name: suprasport_db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  superset:
    build: ./superset
    container_name: suprasport_superset
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      SUPERSET_WEBSERVER_PORT: "8088"
    depends_on:
      - db
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    command:
      - /bin/bash
      - -c
      - |
        superset db upgrade &&
        superset fab create-admin \
            --username $ADMIN_USERNAME \
            --firstname $ADMIN_FIRSTNAME \
            --lastname $ADMIN_LASTNAME \
            --email $ADMIN_EMAIL \
            --password $ADMIN_PASSWORD &&
        superset init &&
        superset run --host 0.0.0.0 --port 8088

  telegram_bot:
    build: ./telegram_bot
    container_name: suprasport_bot
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      DB_HOST: db
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - db

volumes:
  postgres_data:
  superset_home:
